name: Linting

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint:
    name: Running Golangci Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
